pipeline {
    agent any

    options {
        failFast true
        ansiColor('xterm')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                sh "mvn clean install -Dmaven.test.failure.ignore=false"
            }
            post {
                always {
                    junit '**/target/surefire-reports/*.xml'
                }
            }
        }
    }

    post {
        success {
            script {
                if (env.CHANGE_ID) {
                    githubNotify context: 'jenkins/ci', status: 'SUCCESS',
                        description: "Build passed", targetUrl: env.BUILD_URL
                }
            }
        }
        failure {
            script {
                if (env.CHANGE_ID) {
                    githubNotify context: 'jenkins/ci', status: 'FAILURE',
                        description: "Build failed", targetUrl: env.BUILD_URL
                }
            }
        }
    }
}
